version: '3.8'

services:
  db:
    image: postgres:16
    container_name: wedding_postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wedding_network

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - wedding_network

volumes:
  postgres_data:

networks:
  wedding_network: